CREATE EXTERNAL TABLE IF NOT EXISTS docs(line string) STORED AS TEXTFILE LOCATION '${INPUT}';

INSERT OVERWRITE DIRECTORY '${OUTPUT}'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t' 
SELECT word, count(1) as cnt FROM
(SELECT explode(split(line,' ')) as word FROM  docs) w 
GROUP BY word ORDER BY word;

